eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: emt-server-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: emt-server-ribbon
    api-b:
      path: /api-b/**
      serviceId: emt-server-feign